//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShelf_website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestockHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestockHeader()
        {
            this.RestockDetails = new HashSet<RestockDetail>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> RestockDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestockDetail> RestockDetails { get; set; }
    }
}
