//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShelf_website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestockDetail
    {
        public string Id { get; set; }
        public string BookID { get; set; }
        public int QuantityPhysical { get; set; }
        public int QuantityDigital { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual RestockHeader RestockHeader { get; set; }
    }
}
